# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 00:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.PositiveIntegerField()),
                ('friends_count', models.PositiveIntegerField()),
                ('user_id', models.TextField()),
                ('screen_name', models.TextField()),
                ('refreshed_date', models.DateTimeField(default=datetime.datetime(2016, 6, 27, 0, 18, 18, 60091))),
            ],
        ),
    ]
