# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 00:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='refreshed_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 27, 0, 22, 50, 120592)),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='user_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
