# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 02:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160627_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRefresh',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.date(2016, 6, 27))),
            ],
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='refreshed_date',
            field=models.DateField(default=datetime.date(2016, 6, 27)),
        ),
    ]
